# Generated by Django 3.1.6 on 2021-02-01 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=50)),
                ('aim', models.TextField()),
                ('activities', models.TextField()),
                ('number_of_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NgoAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NgoAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credible', models.BooleanField()),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NgoRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_first_name', models.CharField(max_length=200)),
                ('representative_last_name', models.CharField(max_length=200)),
                ('representative_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NgoTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoTWScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tw_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('base_tw_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user_tw_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_data_sources_score', models.FloatField(default=1)),
                ('credible_source_score', models.FloatField(default=0)),
                ('ecosoc_score', models.FloatField(default=0)),
                ('pagerank_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='NgoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_year', models.IntegerField(null=True)),
                ('staff_number', models.IntegerField(default=0)),
                ('member_number', models.IntegerField(default=0)),
                ('working_languages', models.CharField(max_length=400)),
                ('funding', models.CharField(max_length=200)),
                ('president_first_name', models.CharField(max_length=200)),
                ('president_last_name', models.CharField(max_length=200)),
                ('yearly_income', models.CharField(max_length=200)),
                ('type_of_organization', models.ManyToManyField(to='restapi.NgoType')),
            ],
        ),
        migrations.CreateModel(
            name='NgoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('last_edited', models.DateField()),
                ('text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.ngo')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NgoPendingConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('connected_ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_ngo_pending', to='restapi.ngo')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_pending', to='restapi.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NgoMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(null=True)),
                ('info_source', models.ManyToManyField(to='restapi.NgoDataSource')),
            ],
        ),
        migrations.CreateModel(
            name='NgoFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_ngo', models.ManyToManyField(to='restapi.Ngo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NgoEventCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.ngo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.ngoevent')),
            ],
        ),
        migrations.CreateModel(
            name='NgoContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_phone_number', models.CharField(max_length=50)),
                ('ngo_email', models.EmailField(max_length=254, null=True)),
                ('website', models.CharField(max_length=200)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngoaddress')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngorepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='NgoConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('approval_date', models.DateField()),
                ('connected_ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_ngo', to='restapi.ngo')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='restapi.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NgoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ngo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ngo',
            name='accreditations',
            field=models.ManyToManyField(to='restapi.NgoAccreditation'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='branches',
            field=models.ManyToManyField(to='restapi.NgoBranch'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngocontact'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='meta_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ngometadata'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngostats'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='topics',
            field=models.ManyToManyField(to='restapi.NgoTopic'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='tw_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ngotwscore'),
        ),
        migrations.AddConstraint(
            model_name='ngopendingconnection',
            constraint=models.UniqueConstraint(fields=('reporter', 'connected_ngo'), name='unique_pending_connection'),
        ),
        migrations.AddConstraint(
            model_name='ngoeventcollaborator',
            constraint=models.UniqueConstraint(fields=('event', 'collaborator'), name='unique_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='ngoconnection',
            constraint=models.UniqueConstraint(fields=('reporter', 'connected_ngo'), name='unique_connection'),
        ),
    ]
