# Generated by Django 3.1.3 on 2020-12-03 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgoAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NgoAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credible', models.BooleanField()),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_first_name', models.CharField(max_length=200)),
                ('representative_last_name', models.CharField(max_length=200)),
                ('representative_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NgoTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoTWScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tw_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_data_sources_score', models.IntegerField(default=1)),
                ('credible_source_score', models.IntegerField(default=0)),
                ('ecosoc_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NgoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NgoStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_year', models.IntegerField(null=True)),
                ('staff_number', models.IntegerField(null=True)),
                ('member_number', models.IntegerField(null=True)),
                ('working_languages', models.CharField(max_length=400)),
                ('funding', models.CharField(max_length=200)),
                ('president_first_name', models.CharField(max_length=200)),
                ('president_last_name', models.CharField(max_length=200)),
                ('yearly_income', models.CharField(max_length=200)),
                ('type_of_organization', models.ManyToManyField(to='restapi.NgoType')),
            ],
        ),
        migrations.CreateModel(
            name='NgoMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(null=True)),
                ('info_source', models.ManyToManyField(to='restapi.NgoDataSource')),
            ],
        ),
        migrations.CreateModel(
            name='NgoContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_phone_number', models.CharField(max_length=50)),
                ('ngo_email', models.EmailField(max_length=254, null=True)),
                ('website', models.CharField(max_length=200)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngoaddress')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngorepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=50)),
                ('aim', models.TextField()),
                ('activities', models.TextField()),
                ('accreditations', models.ManyToManyField(to='restapi.NgoAccreditation')),
                ('branches', models.ManyToManyField(to='restapi.NgoBranch')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngocontact')),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ngometadata')),
                ('stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.ngostats')),
                ('topics', models.ManyToManyField(to='restapi.NgoTopic')),
                ('tw_score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.ngotwscore')),
            ],
        ),
    ]
