# Generated by Django 3.1.3 on 2020-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoaccreditation',
            name='accreditation',
            field=models.CharField(max_length=400),
        ),
    ]
