# Generated by Django 3.1.5 on 2021-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
