# Generated by Django 3.1.3 on 2020-11-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20201126_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoaccreditation',
            name='accreditation',
            field=models.TextField(),
        ),
    ]
