# Generated by Django 3.1.5 on 2021-01-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_ngotwscore_pagerank_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoconnection',
            old_name='connected_ngo_id',
            new_name='connected_ngo',
        ),
        migrations.RenameField(
            model_name='ngoconnection',
            old_name='reporter_id',
            new_name='reporter',
        ),
    ]
