# Generated by Django 3.1.6 on 2021-02-12 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210208_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngotwscore',
            name='ngo_account_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
