# Generated by Django 3.1.4 on 2020-12-22 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20201204_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngotwscore',
            name='base_tw_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ngostats',
            name='member_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ngostats',
            name='staff_number',
            field=models.IntegerField(default=0),
        ),
    ]
