# Generated by Django 3.1.4 on 2020-12-22 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20201222_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoCommenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('number_of_comments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NgoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('last_edited', models.DateField()),
                ('text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.ngocommenter')),
                ('ngo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.ngo')),
            ],
        ),
    ]
