# Generated by Django 3.1.3 on 2020-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20201126_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ngostats',
            name='type_of_organization',
        ),
        migrations.AddField(
            model_name='ngostats',
            name='type_of_organization',
            field=models.ManyToManyField(to='restapi.NgoType'),
        ),
    ]
