# Generated by Django 3.1.4 on 2020-12-22 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_ngocomment_ngocommenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngotwscore',
            name='user_tw_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
