# Generated by Django 3.1.3 on 2020-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20201128_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngostats',
            name='member_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ngostats',
            name='staff_number',
            field=models.IntegerField(default=0),
        ),
    ]
