# Generated by Django 3.1.4 on 2020-12-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_ngotwscore_user_tw_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngocomment',
            old_name='commenter_id',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='ngocomment',
            old_name='ngo_id',
            new_name='ngo',
        ),
    ]
