# update these when changing the score calculation
BASE_RAW_SCORE_MIN_VALUE = 1.
BASE_RAW_SCORE_MAX_VALUE = 9.

# do not update these
TW_MIN_VALUE = 0
TW_MAX_VALUE = 5


VALID_ACCREDITATIONS = ['ECOSOC', 'ECONOMIC AND SOCIAL COUNCIL', 'ILO', 'COMMONWEALTH FOUNDATION']