# update these when changing the score calculation
RAW_SCORE_MIN_VALUE = 1.
RAW_SCORE_MAX_VALUE = 9.

# do not update these
TW_MIN_VALUE = 0
TW_MAX_VALUE = 5

PAGERANK_MAX_BOOST = 2

RAW_SCORE_AFTER_PAGERANK_MIN_VALUE = RAW_SCORE_MIN_VALUE
RAW_SCORE_AFTER_PAGERANK_MAX_VALUE = RAW_SCORE_MAX_VALUE + PAGERANK_MAX_BOOST


VALID_ACCREDITATIONS = ['ECOSOC', 'ECONOMIC AND SOCIAL COUNCIL', 'ILO', 'COMMONWEALTH FOUNDATION']