# strings should not be nullable, since in this case '' == null ?
# id: int PRIMARY KEY will be autogenerated for each class
# ManyToMany can be null by default, no need to explicitly declare it

from django.db import models


class NgoBranch(models.Model):
    country = models.CharField(max_length=200) # TODO this is essentially a very fancy enum?


class NgoTopic(models.Model):
    topic = models.CharField(max_length=200) # TODO this is essentially a very fancy enum?


class NgoAccreditation(models.Model):
    accreditation = models.CharField(max_length=200) # TODO this is essentially a very fancy enum?


class NgoDataSource(models.Model):  # TODO this is essentially a very fancy enum?
    credible = models.BooleanField()
    source = models.CharField(max_length=200)


class NgoMetaData(models.Model):
    last_updated = models.DateField(null=True)
    info_source = models.ManyToManyField(NgoDataSource) # note: this does not ensure that there is always at least one data source!


class NgoAddress(models.Model):
    street = models.CharField(max_length=200)
    postcode = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)


class NgoRepresentative(models.Model):
    representative_first_name = models.CharField(max_length=200)
    representative_last_name = models.CharField(max_length=200)
    representative_email = models.EmailField()


class NgoContact(models.Model):
    ngo_phone_number = models.CharField(max_length=50)
    ngo_email = models.EmailField(null=True)
    website = models.CharField(max_length=200)
    address = models.ForeignKey(NgoAddress, null=True, on_delete=models.SET_NULL)
    representative = models.ForeignKey(NgoRepresentative, null=True, on_delete=models.SET_NULL)


class NgoStats(models.Model):
    founding_year = models.IntegerField(null=True)
    staff_number = models.IntegerField(null=True)
    member_number = models.IntegerField(null=True)
    working_languages = models.CharField(max_length=400) # TODO store as string or list or reference to language table?
    funding = models.CharField(max_length=200)
    president_first_name = models.CharField(max_length=200)
    president_last_name = models.CharField(max_length=200)


class Ngo(models.Model):
    name = models.CharField(max_length=200) # TODO: unique?
    acronym = models.CharField(max_length=50) # TODO: unique?

    aim = models.TextField() # TODO: should we even keep this?
    activities = models.TextField() # TODO: should we even keep this?

    branches = models.ManyToManyField(NgoBranch)
    topics = models.ManyToManyField(NgoTopic)
    accreditations = models.ManyToManyField(NgoAccreditation)

    stats = models.ForeignKey(NgoStats, null=True, on_delete=models.SET_NULL)
    contact = models.ForeignKey(NgoContact, null=True, on_delete=models.SET_NULL)

    meta_data = models.ForeignKey(NgoMetaData, on_delete=models.PROTECT) # meta data should not be deleted if a ngo is referencing them (we need the data source)
